//Cities
export const FETCH_CITIES_REQUESTED = "FETCH_CITIES_REQUESTED";
export const FETCH_CITIES_SUCCESS = "FETCH_CITIES_SUCCESS";
export const FETCH_CITIES_ERROR = "FETCH_CITIES_ERROR";

//Itineraries
export const FETCH_ITINERARIES_REQUESTED = "FETCH_ITINERARIES_REQUESTED";
export const FETCH_ITINERARIES_SUCCESS = "FETCH_ITINERARIES_SUCCESS";
export const FETCH_ITINERARIES_ERROR = "FETCH_ITINERARIES_ERROR";

//SignUp

export const FETCH_SIGNUP_SUCCESS = "FETCH_SIGNUP_SUCCESS";
export const FETCH_SIGNUP_ERROR = "FETCH_SIGNUP_ERROR";
